logstash-plugins/logstash-output-elasticsearch

- logstash-output-elasticsearch.gemspec
> Update to ES 1.5.0 version

- lib/logstash/outputs/elasticsearch/protocol.rb
- logstash-output-elasticsearch.gemspec
depends on merge of https://github.com/elastic/elasticsearch-ruby/pull/167
> set up manticore timeouts as transport_option settings

- lib/logstash/outputs/elasticsearch.rb
> add description of our retry policy for events

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/http_client.rb
- logstash-output-elasticsearch.gemspec
- spec/integration/outputs/retry_spec.rb
- spec/integration/outputs/update_spec.rb
This is a superset of what's in #227 with the upsert functionality backported.
> Http backports

- lib/logstash/outputs/elasticsearch.rb
Improved docs for Elasticsearch output v2.0. This changeset fixes grammatical errors and uses more clear language than that which preceded it.
> Improve generated inline docs

- lib/logstash/outputs/elasticsearch/http_client.rb
a sniffing action triggers the reload of connections which can
close a socket being used by a running request
this patch introduces a mutex so that bulk operations, template
installation and sniffing don't execute at the same time
> serialize access to the connection pool in es-ruby client

- .travis.yml
- Gemfile
- lib/logstash/outputs/elasticsearch/common.rb
- logstash-output-elasticsearch.gemspec
> update to new event api

- logstash-output-elasticsearch.gemspec
The Changelog was bumped but not the gemspec.
> Bump to 4.0.0

- CHANGELOG.md
- logstash-output-elasticsearch.gemspec
> Bump version to 5.1.1

- lib/logstash/outputs/elasticsearch/common.rb
- lib/logstash/outputs/elasticsearch/http_client.rb
- lib/logstash/outputs/elasticsearch/http_client/pool.rb
> Hide credentials in exceptions and log messages.

- CHANGELOG.md
- logstash-output-elasticsearch.gemspec
> Bump version to 5.1.2

- lib/logstash/outputs/elasticsearch/http_client.rb
- spec/unit/outputs/elasticsearch/http_client_spec.rb
> Handle situations when bulk response has no items

- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/http_client.rb
- lib/logstash/outputs/elasticsearch/http_client/pool.rb
- lib/logstash/outputs/elasticsearch/http_client_builder.rb
- spec/unit/outputs/elasticsearch/http_client/pool_spec.rb
> Add option to use an absolute healthcheck path

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/http_client.rb
- lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb
- lib/logstash/outputs/elasticsearch/http_client_builder.rb
- logstash-output-elasticsearch.gemspec
- spec/integration/outputs/index_spec.rb
Signed CLA: https://elasticsearch.na1.echosign.com/public/viewAgreement?tsid=CBFCIBAA3AAABLblqZhA5OlzpZs-E9WCGvdpyuUvHIwxrJQNglMowf-fapfJDZTMGQ03XLOsUjaqxEfO-HSUTWVWRHYv8Y_QN-fGamcoi&
> Added gzip compression support

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch/common.rb
- logstash-output-elasticsearch.gemspec
> fix incorrect name of event to be written to dlq

- .travis.yml
- CHANGELOG.md
- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/common.rb
- lib/logstash/outputs/elasticsearch/http_client.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch_spec.rb
Moved #647 to here since I accidentally closed the branch . which is apparently fatal.
> Retries 7x

- lib/logstash/outputs/elasticsearch/template_manager.rb
> Get maximum version with max() instead #663

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch/http_client/manticore_adapter_spec.rb
> Fix error in instantiating bad response code exceptions

- lib/logstash/outputs/elasticsearch/elasticsearch-template-es7x.json
improves support for elasticsearch 7.x, see more in https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/701
> add template for elasticsearch 7.x

- LICENSE
> [skip ci] update license to 2018

- docs/index.asciidoc
> Fix typo "elasticseach’s" => "elasticsearch’s"

- lib/logstash/outputs/elasticsearch/common.rb
- spec/unit/outputs/elasticsearch_spec.rb
> assume document type is _doc for ES 7.x clusters

- docs/index.asciidoc
> Minor fix link representation

- CHANGELOG.md
- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/http_client.rb
- lib/logstash/outputs/elasticsearch/http_client_builder.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch_spec.rb
fixes https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/723
> Allow configuration of custom headers

- docs/index.asciidoc
Add ILM upgrade note from https://github.com/elastic/logstash-docs/pull/667 to source file so that content will be persisted when we regenerate plugin docs
> [Doc] Add ILM upgrade note

- lib/logstash/outputs/elasticsearch/common.rb
- lib/logstash/outputs/elasticsearch/common_configs.rb
- spec/integration/outputs/parent_spec.rb
- spec/unit/outputs/elasticsearch_spec.rb
> Revert document type deprecation

- docs/index.asciidoc
> corrected logstash syntax

- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/common_configs.rb
:scissors: - align with filter/input ES plugin docs
> Docs: fix typos introduced recently

- docs/index.asciidoc
~ilm_rollover_pattern~ ilm_rollover_alias
> [DOC] Replace setting name in ilm_rollover note

- CHANGELOG.md
- logstash-output-elasticsearch.gemspec
Bump version to pick up doc change in #919
> Version bump to 10.3.2

- CHANGELOG.md
> Update changelog to include integration test fix

- CHANGELOG.md
- CONTRIBUTORS
- docs/index.asciidoc
- logstash-output-elasticsearch.gemspec
> [DOC] Explicitly call out permissions

- .ci/docker-setup.sh
Use the snapshot builds from `docker.elastic.co`, rather than from the artifacts
repo.
This enables the removal of code to download architecture specific artifacts for
versions of Logstash with a bundled JDK. Docker pull will retrieve the architecture
appropriate version automatically, simplifying the path towards multi-architecture test
suites for plugins.
> Use docker pull for snapshots

- docs/index.asciidoc
> Docs: mention synthetics being supported

- CHANGELOG.md
- logstash-output-elasticsearch.gemspec
Fix bad version bump (never published) happened with #1038
> Fixed bad version bumpd 11.1.0 instead of 11.6.0

- CHANGELOG.md
Updates changelog to add links to PRs and issues for easier reference.
> Add PR/issue links to changelog

- .github/workflows/main.yml
> Add to project action

- CHANGELOG.md
Updates changelog to point to fix rather than to only the issue
> Update changelog entry with more details

- CHANGELOG.md
Fix the changelog format for version 11.12.3
> Fix changelog format for version 11.12.3

- CHANGELOG.md
- logstash-output-elasticsearch.gemspec
> Bump version to release latest changes

- logstash-output-elasticsearch.gemspec
CHANGELOG on main already includes the entry for 11.15.2 from #1105 -> https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/main/CHANGELOG.md#11152
> actual version bump :facepalm:

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch.rb
- logstash-output-elasticsearch.gemspec
Resolves #1141 by moving ssl standardization to `#initialize`
> fix: move ssl standardization to #initialize
