- lib/logstash/outputs/elasticsearch/elasticsearch-template.json
This causes recent (see: master) builds of elasticsearch to fail new
index create when drawing from the default mapping. "path": "full" is no
longer supported, but the default behavior in elasticsearch is such that
operations that rely on the path notation should still function
normally.
Fixes #94
> Remove `"path": "full"` from geoip mapping

- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/protocol.rb
- spec/outputs/elasticsearch_spec.rb
I have added support for routing when indexing documents.
> Added support for routing parameters.

- lib/logstash/outputs/elasticsearch.rb
- spec/outputs/elasticsearch_spec.rb
> log about support for create_unless_exists in http protocol

- lib/logstash/outputs/elasticsearch.rb
- spec/outputs/elasticsearch_spec.rb
This was originally done to close https://github.com/elastic/logstash/issues/1901 and pr for this was here: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/4, but does not seem to be
clear enough and necessary. It leads to lazy behavior, and makes it
difficult to take control of the exact template pattern.
> revert index template wildcard overwriting.

- lib/logstash/outputs/elasticsearch.rb
some log messages were referencing @host field, even when
the field was nil and not applicable (when protocol was node).
I do not see the benefit of these messages, as the exception is thrown in case of emergency anyways. and that exception will be logged.
Closes #120.
> removed some debug log lines

- lib/logstash/outputs/elasticsearch.rb
update to: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/105
in response to: https://github.com/logstash-plugins/logstash-output-elasticsearch/commit/fa80d95dea7e30682920d861e4c44d673892b20e#commitcomment-11036062
> add descriptive text about why a field is deprecated

- lib/logstash/outputs/elasticsearch/protocol.rb
- spec/integration/outputs/elasticsearch/node_spec.rb
during the `node_spec.rb` tests, NodeClient does not get
cleaned-up correctly. Since we are just testing a utility
function within the class, I have changed the `#hosts` method
to be a class variable (still private). This should now let
`bundle exec rspec --tag integration` terminate.
> NodeClient does not get cleaned up during tests

- spec/integration/outputs/templates_spec.rb
Elasticsearch 2.0 will not support facets anymore, this is
an update to the tests to move to using aggregations
> [Test] Facets are deprecated in favor of Aggregations.

- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/http_client.rb
- lib/logstash/outputs/elasticsearch/protocol.rb
- spec/integration/outputs/retry_spec.rb
- spec/unit/outputs/elasticsearch/protocol_spec.rb
This addresses #219 by improving error messages in the event that ES is down. 
It also cleans up the HTTP support by moving protocol.rb to http_client.rb
> Better error reporting

- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/http_client.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch_spec.rb
Allows the user to configure network timeouts to Elasticsearch.
Default is the previous behavior: no timeout
For #260
> New setting: timeout

- lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb
- lib/logstash/outputs/elasticsearch/http_client/pool.rb
- lib/logstash/outputs/elasticsearch/safe_url.rb
- spec/unit/safe_url_spec.rb
Previously, a 403 error would log this:
> Got response code '403' contact Elasticsrearch at URL 'http://foo:bar@localhost:9200/'
This caused a leak in credentials.
> Hide user and password from the url.

- lib/logstash/outputs/elasticsearch/elasticsearch-template-es5x.json
- spec/unit/outputs/elasticsearch/template_manager_spec.rb
This adds a version value of today's date (`20160915`) as the version. Any change to the template should increase the version number (change to that date), thus making it easier to detect changes.
As this is the first release of 5.x, it really is somewhat moot, but any future release may also choose to build in variable for the 5.x change so that the file only needs to be loaded _if_ the version actually needs to be replaced.
Closes #477
> Add "version" to 5.x template

- CHANGELOG.md
- logstash-output-elasticsearch.gemspec
- spec/es_spec_helper.rb
`longeshoreman` depends on `docker-api` which now wants to use ruby 2.0. We don't use longeshoreman anymore in our tests, so removing all together.
> Remove docker dependency

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch/common.rb
- lib/logstash/outputs/elasticsearch/common_configs.rb
- logstash-output-elasticsearch.gemspec
Previously, ingest pipeline config was not setup to use
event dependent configuration, but now it is.
> Add `sprintf` or event dependent configuration when specifying ingest pipeline

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/http_client.rb
- lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb
- lib/logstash/outputs/elasticsearch/http_client/pool.rb
- lib/logstash/outputs/elasticsearch/http_client_builder.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/http_client_builder_spec.rb
- spec/unit/outputs/elasticsearch/http_client/pool_spec.rb
This commit removes absolute_healthcheck_path and query_parameters
and introduces two new configs settings: `sniffing_path` and `bulk_path`.
The behaviour of the healthcheck, bulk and sniffing paths is now:
- if not set: the default value will be used
- if not set and path is also set: the default is appended to path
- if set: the set value will be used, ignoring the default and path values
These three settings also support query parameters, which will be
carried and included in the request to elasticsearch
> introduce customization of bulk, healthcheck and sniffing paths

- lib/logstash/outputs/elasticsearch/common.rb
Fixes #515 by removing the accidentally-unhelpful log message that was
smply logging "Action" with no context.
> Make it more clear when bulk actions are being retried.

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/http_client.rb
- lib/logstash/outputs/elasticsearch/http_client_builder.rb
- logstash-output-elasticsearch.gemspec
- spec/integration/outputs/compressed_indexing_spec.rb
- spec/integration/outputs/index_spec.rb
This PR:
* Adds `http_compression` to enable compressing both the request and response.
* Response compression is handled automatically by HTTPCommons, but the correct headers (`Accept-Encoding`) needs to be sent.
* Adds a new file for compressed indexing tests. The previous test attempt was borked
* Bumps version
Follow up from #559
> Change the compression feature to include gzip'ing responses and requests

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch.rb
- logstash-output-elasticsearch.gemspec
Adds compatibility note requested in https://github.com/elastic/logstash/issues/6718
@acchen97 Please review.
> Add plugin level required to support sending content-type headers

- lib/logstash/outputs/elasticsearch/common.rb
- spec/integration/outputs/retry_spec.rb
Also retry policy has been changed. This is mostly motivated from #572 and the use of DLQ.
We now retry everything except for 400 and 409.
Fixes #572
> Use a dead letter queue to handle mapping errors.

- lib/logstash/outputs/elasticsearch/elasticsearch-template-es5x.json
- lib/logstash/outputs/elasticsearch/elasticsearch-template-es6x.json
fixes #588
Since the 5.x and 6.x templates override the default keyword mapping
in elasticsearch which defaults to `"ignore_above": 256`, the templates
should include this clause otherwise the burden of dealing with this
situation passes instead to Lucene.
Also, looking at the history I see no rationale for removing it in the first place, maybe it was a mistake?
> introduce ignore_above in string_fields default mapping for keywords

- CHANGELOG.md
- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch/common.rb
- lib/logstash/outputs/elasticsearch/common_configs.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch_spec.rb
* make deprecated options :flush_size and :idle_flush_time obsolete
* remove obsolete options :max_retries and :retry_max_items
> perform some deprecation/obsoletion cleanups

- CHANGELOG.md
- ci/run.sh
- lib/logstash/outputs/elasticsearch/common.rb
- lib/logstash/outputs/elasticsearch/common_configs.rb
- logstash-output-elasticsearch.gemspec
- spec/integration/outputs/parent_spec.rb
This PR adds a new parameter `join` to support elasticsearch 6.x join field type and associated changes in the parent/child feature, along with a test for it. It also excludes existing parent/child specs from running if the tested ES is 6.x or higher.
The specs are currently failing since scripting also requires changes to make this plugin compatible with ES 6.x, but I believe these are out of scope for this PR.
fixes https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/602
> Fix parent/child support for elasticsearch 6.x and support join type field

- lib/logstash/outputs/elasticsearch/http_client.rb
- lib/logstash/outputs/elasticsearch/http_client/pool.rb
- lib/logstash/outputs/elasticsearch/template_manager.rb
- spec/unit/outputs/elasticsearch/http_client/pool_spec.rb
- spec/unit/outputs/elasticsearch/http_client_spec.rb
- spec/unit/outputs/elasticsearch/template_manager_spec.rb
* have the connection pool remember the elasticsearch version for each connection
* the http_client can get a list of all these versions
* the sniffing now knows the version of elasticsearch the _nodes/http came from
* the template manager installs the template version of the biggest major version of any connected client
This PR is still not production ready but seems to work: it makes the pool track the info about the es versions of each node.
Then the HttpClient, TemplateManager and others can pull that list and decide what to do.
> new elasticsearch version handling

- lib/logstash/outputs/elasticsearch/common.rb
- lib/logstash/outputs/elasticsearch/common_configs.rb
- spec/integration/outputs/parent_spec.rb
* add support for join based parent indexing (available in ES 5.6 and 6.0)
* dont use ftw on parent integration specs
backport of #632 to 7.x
> add support for join based parent indexing (backport of #632 to 7.x)

- docs/index.asciidoc
- spec/integration/outputs/painless_update_spec.rb
Also adds documentation explaining that for ES 6 it's necessary to set the `script_lang` parameter to empty string (`""`).
fixes https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/638
replaces #642
> fix stored painless script integration testing for es 6 and above

- .travis.yml
due to elasticsearch master containing breaking changes as it moves to 7.0.0,
it's not required that the tests pass for this particular scenario until
it reaches closer to 7.0.0-alpha1
> allow failures in es master

- CHANGELOG.md
- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch/common.rb
- lib/logstash/outputs/elasticsearch/http_client.rb
- lib/logstash/outputs/elasticsearch/http_client/pool.rb
- lib/logstash/outputs/elasticsearch/template_manager.rb
- logstash-output-elasticsearch.gemspec
- spec/integration/outputs/compressed_indexing_spec.rb
- spec/integration/outputs/index_spec.rb
- spec/unit/outputs/elasticsearch/http_client/pool_spec.rb
- spec/unit/outputs/elasticsearch/template_manager_spec.rb
- spec/unit/outputs/elasticsearch_spec.rb
- spec/unit/outputs/error_whitelist_spec.rb
aims to replace https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/709
This PR ensures the event field "type" isn't used as a document_type if elasticsearch cluster is on 6.0
> Only use the type field for the event for ES versions < 6.0

- ci/run.sh
see more in https://github.com/elastic/elasticsearch/pull/27885
an example of failure: https://travis-ci.org/logstash-plugins/logstash-output-elasticsearch/jobs/321736196#L1605
> use gradle 4.3 because es 7 needs it

- lib/logstash/outputs/elasticsearch/elasticsearch-template-es7x.json
Override Elasticsearch default sharding via logstash-specific index template.
> Set number_of_shards to 1

- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/common.rb
- lib/logstash/outputs/elasticsearch/http_client.rb
- lib/logstash/outputs/elasticsearch/http_client/pool.rb
- lib/logstash/outputs/elasticsearch/http_client_builder.rb
- spec/integration/outputs/metrics_spec.rb
- spec/integration/outputs/sniffer_spec.rb
- spec/unit/outputs/elasticsearch/http_client_spec.rb
~~- number of sniffing requests performed~~
~~- number of bulk_requests measured before right before executing the
request~~
~~- number of concurrent bulk_requests~~
~~- number of bulk retries~~
metrics calculated:
```ruby
{
"bulk_requests": {
"responses": {  # counts per top level status code returned in the bulk response
"200": 346300,
"201": 712,
"404": 61,
"429": 36
},
"successes": 346819,  # successful bulk requests with no errors (sum of 200 and 201 minus partial_successes)
"failures": 23,         # no http response from ES. will be retried. see point 1 above for causes
"partial_successes": 134,  # bulk request successful (status 20X) but contains errors
"drops": 5,   # bulk request dropped
},
"documents": {
"successes": 173409500,
"retryable_failures": 450, …
```
> add a few metrics to the plugin

- CHANGELOG.md
- logstash-output-elasticsearch.gemspec
changelog computed from:
```
% git lg v9.0.3..master
* b0c0c54 - (origin/master, origin/HEAD, master) Minor fix link representation (3 days ago) <Pavel Alexeev aka Pahan-Hubbitus>
* 71b2e53 - assume document type is _doc for ES 7.x clusters (#747) (3 days ago) <João Duarte>
* 353e4f5 - add a few metrics to the plugin (#585) (3 days ago) <João Duarte>
* 9f3fffd - Set number_of_shards to 1 (4 days ago) <Glen Smith>
* 32ca02c - Update index.asciidoc (8 days ago) <Thomas Decaux>
* 7575f62 - Fix typo "elasticseach’s" => "elasticsearch’s" (8 days ago) <Takahiro Ethan Ikeuchi>
* 7dde2de - Merge pull request #385 from dchauviere/issue_239 (3 weeks ago) <Guy Boertje>
* 5272a72 - Fix #239 - interpolated action "update" don't get params "upsert" and "script" (3 weeks ago) <David Chauviere>
```
> bump version to 9.1.0

- lib/logstash/outputs/elasticsearch/http_client.rb
This would cause the exception handler in common.rb to fail, since it expects to be able to call .sanitized on the URL
fixes https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/662
> Fix incorrect logging of non-SafeURI as BadResponseCode

- docs/index.asciidoc
Add this example : 
`script => "ctx._source.message = event.get('message')"`
> Add an example for "script" option in documentation

- .travis.yml
- ci/run.sh
no point in testing against logstash 6.x as 6.0.0 shipped with es output 9.0.0
remove references to 6.0.0-beta2, update version of logstash 5.6 from 5.6.0 to 5.6.9
> cleanup travis ci file for 7.x branch

- spec/unit/outputs/elasticsearch/http_client_spec.rb
Unit tests were failing after a change introduced with Javafication of NamespacedNullMetric
> Fix http_client_spec.rb unit tests

- lib/logstash/outputs/elasticsearch/http_client.rb
- spec/unit/outputs/elasticsearch/http_client_spec.rb
Implement https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch/http_client.rb#L118 from master in 7.x.
Avoid an infinite loop caused by sending a bulk request to Elasticsearch with a zero body size.
Issue #736 
https://discuss.elastic.co/t/inifinite-loop-encountered-a-retryable-error-400-error-from-elasticsearch/119290
https://discuss.elastic.co/t/logstash-5-6-1-inifinite-loop-encountered-a-retryable-error/101753
> Avoid infinite loop by checking for zero body size #736

- spec/integration/outputs/index_spec.rb
by default devutils sets up the following exclusions:
{:redis=>true, :socket=>true, :performance=>true,
:couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true,
:export_cypher=>true, :integration=>true, :windows=>true}
However there was a test suite that ran integration tests against a
secured elasticsearch instance, tagged with `integration_secure`
This meant that a normal `bundle exec rspec` would run these tests
and fail. This PR replaces the `integration_secure` tag with the
`elasticsearch_secure` so that the tests are excluded by default too.
> set secure tag so integration test is excluded by default

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/common.rb
- logstash-output-elasticsearch.gemspec
- spec/es_spec_helper.rb
- spec/integration/outputs/compressed_indexing_spec.rb
- spec/integration/outputs/index_spec.rb
- spec/integration/outputs/no_es_on_startup_spec.rb
- spec/unit/outputs/elasticsearch/http_client_spec.rb
- spec/unit/outputs/elasticsearch_proxy_spec.rb
- spec/unit/outputs/elasticsearch_spec.rb
- spec/unit/outputs/elasticsearch_ssl_spec.rb
Prior to this commit, if Elasticsearch was down during Logstash startup,
one of two outcomes would occur:
If Elasticsearch was still down when the first events arrived, Logstash
would immediately exit with an error
If Elasticsearch was up when the first events arrived, Logstash would
accept the messages, but would the template for the index would not
be installed.
This commit will install the template only after a successful call to
Elasticsearch has been made. New messages will block until connectivity
to Elasticsearch is re-established and the template has been installed
fixes #715 
fixes #750
> Improve plugin behavior when Elasticsearch is down on startup

- spec/es_spec_helper.rb
- spec/integration/outputs/index_spec.rb
by default devutils exludes a set of spec tags but that set doesn't
include this plugin's "secure_integration" tag. This PR adds that tag
to the default set of exclusions.
> fix secure integration spec tagging

- docs/index.asciidoc
The `truststore` setting also accepts `jks` and `p12`.
This makes it's description closer to `keystore`, in regards to file type.
> Update `truststore` description

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch/http_client/pool.rb
- logstash-output-elasticsearch.gemspec
There are multiple logging statements in this plugin that are either superfluous or could be moved to a more verbose level. This PR changes a couple of them to reduce overall logging fatigue when using the ES output.
> reduced logging verbosity and unecessary upper case error message

- docs/index.asciidoc
Resolves: logstash-plugins/logstash-output-elasticsearch#819
> docs: flag as `no_codec` to reduce confusion

- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch/common.rb
- lib/logstash/outputs/elasticsearch/common_configs.rb
- lib/logstash/outputs/elasticsearch/ilm.rb
- lib/logstash/outputs/elasticsearch/template_manager.rb
- spec/es_spec_helper.rb
- spec/integration/outputs/compressed_indexing_spec.rb
- spec/integration/outputs/ilm_spec.rb
- spec/integration/outputs/index_spec.rb
- spec/unit/outputs/elasticsearch_spec.rb
- spec/unit/outputs/error_whitelist_spec.rb
Adds a new (default) configuration option for `ilm_enabled` - `auto`. Using `auto` will enable ILM if the target Elasticsearch cluster is > 7.0, and has the ILM feature enabled and available.
> Add support for 'auto' setting for ilm_enabled

- lib/logstash/outputs/elasticsearch/common.rb
- lib/logstash/outputs/elasticsearch/ilm.rb
- lib/logstash/outputs/elasticsearch/template_manager.rb
- spec/integration/outputs/ilm_spec.rb
When customers were managing their own templates, but not using ilm,
templates could still be overwritten. This commit fixes the logic
to only overwrite templates when ilm is in use
> Fix issue with templates being erroneously overwritten

- docs/index.asciidoc
I think that the "update a document if not already present" only works with the `doc_as_upsert` option.  The `upsert` option adds data to the document if the document does not exist I think.
Some more explicit documentation for both `upsert` and `doc_as_upsert` would also be helpful
> Corrected documentation for `action => update`

- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/http_client/pool.rb
- spec/es_spec_helper.rb
- spec/unit/outputs/elasticsearch/http_client/pool_spec.rb
when running a default logstash distribution we should error out if the elasticsearch distribution is oss. this makes logstash behave like beats
> check if ES is licensed before pushing out events to it

- CHANGELOG.md
- docs/index.asciidoc
- logstash-output-elasticsearch.gemspec
Wording fix in response to request from Support
> [Doc]Update wording on ilm_enabled setting and bump to v10.2.1

- docs/index.asciidoc
This PR adds some background on preferring a single Elasticsearch output vs multiple Elasticsearch outputs when events are routed to multiple indices within the same Cluster
> [DOC] Add best practices on single/multiple Elasticsearch outputs

- CHANGELOG.md
- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/common.rb
- lib/logstash/outputs/elasticsearch/common_configs.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch_spec.rb
should be fairly straight-forward: 
- **cloud_id** is a substitute for the *hosts* setting (one can not use both)
- **cloud_auth** is an *user/password* alternative
resolves: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/893
~~TODO documentation for new options~~
> Feat: Added support for cloud_id and cloud_auth

- lib/logstash/outputs/elasticsearch.rb
- spec/unit/outputs/elasticsearch_spec.rb
SNAPSHOTS still failing ... but some :red_circle: introduced at https://github.com/logstash-plugins/logstash-output-elasticsearch/commit/3b6aa8556e8c5cc3a55b2fa8059a4dda8145ce02 is resolved
> Test: get (most) specs passing on CI

- CHANGELOG.md
- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch_proxy_spec.rb
a convenient feature when users are using env variables for proxy
e.g. `proxy => ${LS_PROXY:}`. 
empty proxy host settings are common to be ignored by libraries ...
> Fix: handle proxy => '' as if none was set

- spec/es_spec_helper.rb
- spec/integration/outputs/create_spec.rb
- spec/integration/outputs/ilm_spec.rb
- spec/integration/outputs/ingest_pipeline_spec.rb
- spec/integration/outputs/no_es_on_startup_spec.rb
- spec/integration/outputs/retry_spec.rb
- spec/integration/outputs/templates_5x_spec.rb
- spec/integration/outputs/templates_spec.rb
Elasticsearch `7.6` introduced an `ilm-history` which caused a number of
tests to fail. Certain ILM tests were failing because they were trying to
delete ILM policies tied to histories, while others were failing due to the
search query being applied across all indices, rather than being targeted.
This commit fixes the search criteria across a number of tests, and avoids
trying to delete any `ilm-history` policies, which is not allowed due to items
existing in the associated history indices.
> Fix integration tests for Elasticsearch 7.6+

- spec/es_spec_helper.rb
- spec/integration/outputs/ilm_spec.rb
Later versions of the Elasticsearch mandate a `name` parameter to the
`exists_alias` method. This commit updates the tests to include that
parameter.
Additionally, there are some fixes to move towards an "inclusion" list
of policies to delete, rather than an "exclusion" list.
> More fixes to Elasticsearch output build

- CHANGELOG.md
- docs/index.asciidoc
- logstash-output-elasticsearch.gemspec
Contains cherry-picks from #921 and adds a version bump
> Replace link to Cloud trial with attribute and bump to v10.3.3

- CHANGELOG.md
Per chat with @robbavey , ilm_enabled's 'auto' setting was actually added in 9.4.0 (but the default remained 'false').  10.0.0 is when we switched the default to 'auto'.
This PR updates the changelog accordingly.
> Adding 9.4.0 changelog

- CHANGELOG.md
- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch/common_configs.rb
- logstash-output-elasticsearch.gemspec
Resolves #876 
Default value listed for `index` was listed as `logstash-%{+YYYY.MM.dd}`
This PR corrects the default value to `logstash-%{+yyyy.MM.dd}`
> [Doc]Fix default value for index and bump to v.10.4.0

- CHANGELOG.md
- docs/index.asciidoc
- logstash-output-elasticsearch.gemspec
Call out _type change from `doc` to `_doc` in documentation
> [Doc]Add note about _type setting change from doc to _doc

- CHANGELOG.md
- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/common.rb
- lib/logstash/outputs/elasticsearch/http_client_builder.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch_spec.rb
Related to https://github.com/elastic/logstash/issues/11788
Fixes #908
- Add support for [elasticsearch API key](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-api-key.html) authentication using the `api_key` option
- SSL must be enabled
- Only one authentication method must be specified out of (`user`/`password`, `cloud_auth` and `api_key`)
- Related specs
- Manually tested against a cloud cluster
> add elasticsearch API key support

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/common.rb
- logstash-output-elasticsearch.gemspec
Related to #934 and https://github.com/elastic/logstash/pull/11818
This patch release is intended essentially to solve the `cloud_id` problem reverted fix  https://github.com/elastic/logstash/pull/11800 for 7.6 and 7.7.
> make credentail and host setup happen in build_client

- CHANGELOG.md
- docs/index.asciidoc
- logstash-output-elasticsearch.gemspec
> [DOC]Remove outdated compatibility notices and rework cloud notice

- CHANGELOG.md
- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch/common.rb
- logstash-output-elasticsearch.gemspec
Because Logstash Core v7.7.0-v7.8.x override the `use_event_type?` in a
monitoring implelentation's subclass with a required (and ignored) `client`
argument, when we send `use_event_type?` internally, we must send an argument
or else we break compatibility with those versions of Logstash.
This change re-adds the required argument and modifies our call-site to send
with an arity of 1, re-names the resulting local variable to be descriptive
of our intent, and adds commentary to prevent future accidental breakage.
> Fix breakage caused by external use of our internal API

- docs/index.asciidoc
See https://github.com/elastic/elasticsearch/pull/56899, Elasticsearch disables compression if HTTPS is enabled.
> [Doc] Update http compression in Elasticsearch

- docs/index.asciidoc
If I don't provide the `ilm_policy` config. The default value is `logstash_policy`.
I created a dockerfile
```
FROM docker.elastic.co/logstash/logstash:7.8.1
RUN rm -f /usr/share/logstash/pipeline/logstash.conf
ADD pipeline/ /usr/share/logstash/pipeline/
ADD config/ /usr/share/logstash/config/
``` 
And the output from the docker file is the following 
```
Installing ILM policy {"policy"=>{"phases"=>{"hot"=>{"actions"=>{"rollover"=>{"max_size"=>"50gb", "max_age"=>"30d"}}}}}} to _ilm/policy/logstash-policy
```
> Updated default value ilm_policy

- docs/index.asciidoc
ILM pattern number part is 0-padded 6 digits wide string
> [Doc] added the ILM pattern note

- CHANGELOG.md
- docs/index.asciidoc
- logstash-output-elasticsearch.gemspec
[Cloud rework](https://github.com/elastic/logstash/pull/11884) broke some links from the plugins. This PR updates the links and points one level up in docs to give user a bit more context for logstash->cloud. 
Fixes: #974
> Doc: Update links to logstash-to-cloud docs

- .ci/docker-setup.sh
Since the 8.x docker images for Logstash are arch-specific (relying on the base install with embedded arch-specific JVM), they no longer will have the same file names we relied on for 7.x causing builds to fail when looking up the URL for the most recent snapshot.
This PR refactors the code that finds the URL for docker image snapshots to find appropriate artifacts, whether the listing includes no-arch or `x86_64`-arch artifacts. It also adds helpful logging when none of the items can be found, and breaks the code into a function for reuse when loading the elasticsearch image.
Prior to this change, failure to load a URL resulted in a blind error:
~~~
null
curl: (6) Could not resolve host: null
~~~
After this change, an error looking up the URL will be much more informative:
~~~ …
> ci: look for arch-specific snapshots when necessary

- docs/index.asciidoc
Replaces free text with an attribute to help keep content up-to-date and consistent across documents.
~DO NOT MERGE until after elastic/docs#1815 has been merged.~  DONE
> [Doc]Replace free text with attribute for cloud trial

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch/http_client.rb
- lib/logstash/outputs/elasticsearch/template_manager.rb
- lib/logstash/outputs/elasticsearch/templates/ecs-disabled/elasticsearch-8x.json
- logstash-output-elasticsearch.gemspec
- spec/es_spec_helper.rb
- spec/fixtures/template-with-policy-es8x.json
- spec/integration/outputs/ilm_spec.rb
- spec/integration/outputs/metrics_spec.rb
- spec/unit/outputs/elasticsearch/http_client_spec.rb
- spec/unit/outputs/elasticsearch/template_manager_spec.rb
- spec/unit/outputs/elasticsearch_spec.rb
Elasticsearch's /_template API is being deprecated in 7.8, this PR migrate to Composable Templates (see: elastic/elasticsearch#53101).
Fix: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/944
- Use the new endpoint `_index_template` to manage template if elasticsearch version >= 8
- Add a new template 8x with `priority` set for default usage
- Data stream option will be handled in elasticsearch data stream plugin 
- Bump version
> Implement Composable Templates to support Elasticsearch 8.0

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/http_client.rb
- lib/logstash/outputs/elasticsearch/http_client/pool.rb
- lib/logstash/outputs/elasticsearch/http_client_builder.rb
- lib/logstash/outputs/elasticsearch/ilm.rb
- lib/logstash/outputs/elasticsearch/license_checker.rb
- lib/logstash/plugin_mixins/elasticsearch/common.rb
- lib/logstash/plugin_mixins/elasticsearch/noop_license_checker.rb
- spec/unit/outputs/elasticsearch/http_client/pool_spec.rb
- spec/unit/outputs/license_check_spec.rb
This is work toward Data Streams integration elastic/logstash#12178
Specific elasticsearch methods are now into the main elasticsearch class file and shared methods have been moved into the PluginMixins::ElasticSearch::Common namespace. The license checking code has been externalized and can now be specified as argument to the `build_client` method.
This is code refactorting that has no end-user impact.
> common code refactoring

- CHANGELOG.md
- logstash-output-elasticsearch.gemspec
This is to merge after #973 and #976 to wrap these to PRs. 
This is work toward Data Streams integration elastic/logstash#12178
> bump version to 10.8.0

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch/http_client/pool.rb
- logstash-output-elasticsearch.gemspec
Hash#fetch returns the default value when the hash does not contain a value for the key but here we set that value to `nil`. This is a safer construct that will work for `nil` value or no-value.
> fix bug in choosing the NoopLicenseChecker

- CHANGELOG.md
- docs/index.asciidoc
- logstash-output-elasticsearch.gemspec
Standardize links to other Elastic docs to use shared attributes.
Wrap long lines for consistency and readability. 
Bump to v.10.8.2
> Doc:Replace cross doc links with attributes

- CHANGELOG.md
- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch.rb
- logstash-output-elasticsearch.gemspec
- spec/integration/outputs/retry_spec.rb
- spec/unit/outputs/elasticsearch_spec.rb
With ES 7.10.0 a deprecation log line about types removal is printed for each request (index/bulk) that contains the deprecated index `_type`.
This led to possible flood of deprecation logs on Elasticsearch, tracked in https://github.com/elastic/elasticsearch/issues/69188.
This commit removes the implicit set of type when connected to ES7 unless the user doesn't specify explicitly the type.
Related to #915
> Remove `type` when connecting to ES 7 and user doesn't specify it

- CHANGELOG.md
- lib/logstash/plugin_mixins/elasticsearch/common.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch_spec.rb
we've seen some weird behavior on ES **7.10.2** (but also with **7.11.1**) where a _bulk request to
index 69 documents returned 135 entries
this leads to an ugly `NoMethodError: undefined method ``[]' for nil:NilClass`
resolves #989
> Feat: assert returned item count from _bulk

- .ci/elasticsearch-run.sh
- CHANGELOG.md
- lib/logstash/outputs/elasticsearch/http_client.rb
- lib/logstash/plugin_mixins/elasticsearch/common.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch/http_client_spec.rb
- spec/unit/outputs/elasticsearch_spec.rb
The Http Client breaks batches of actions into sub-batches that are up to 20MB
in size, sending larger actions as batches-of-one, and zips the responses
together to emulate a single batch response from the Elasticsearch API.
When an individual HTTP request is rejected by Elasticsearch (or by an
intermediate proxy or load-balancer) with an HTTP/1.1 413, we can emulate
the error response instead of blowing an exception through to the whole batch.
> fix: prevent sub-batch 413's from blocking whole batch

- CHANGELOG.md
- docs/index.asciidoc
- logstash-output-elasticsearch.gemspec
> Doc: Fixed list item to address broken link

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/data_stream_support.rb
- lib/logstash/plugin_mixins/elasticsearch/common.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch_spec.rb
since [Data Streams](https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/988), we refactored to pass down event data directly instead of the [previous `event.to_hash` mapping in `safe_bulk`](https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/988/files#diff-221ddb62bde6d62966fab1051387ded7513fffd575cf0706a5f3a94ad2d31307L270) (doing so potentially on every retry)
there seemed to have been no reason to keep the original event around (well turns except with DLQ).
besides practical reasons the early `event.to_hash` also addressed a requirement to ... [sync data stream fields without effecting the original event](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/v11.0.0/lib/logstash/outputs/elasticsearch/data_stream_support.rb#L148). …
> Fix: DLQ expects us to pass down an event

- .ci/Dockerfile.elasticsearch
- CHANGELOG.md
- lib/logstash/outputs/elasticsearch/http_client/pool.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch/http_client/pool_spec.rb
- spec/unit/outputs/elasticsearch_spec.rb
Update client behavior to match functionality of 7.14+
----
> Add preflight check on Elasticsearch before connecting

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch/http_client/pool.rb
- logstash-output-elasticsearch.gemspec
Some Gem classes was referenced from open Logstash lexical scope while it should refer from the global.
> Fix referencing Gem classes from global lexical

- CHANGELOG.md
- Rakefile
- logstash-output-elasticsearch.gemspec
Updates our vendoring definition so that when `ecs_compatibility => v1` is specified the ECS v1.12.1 templates are loaded.
> ecs: update v1 to ECS v1.12.1

- CHANGELOG.md
- Rakefile
- lib/logstash/outputs/elasticsearch.rb
- logstash-output-elasticsearch.gemspec
- spec/integration/outputs/templates_spec.rb
- spec/unit/outputs/elasticsearch/template_manager_spec.rb
- transforms ECS-generated template for ES7 into ES8-compatible index_template
- adds _PREVIEW_ of 8.0 templates for Elasticsearch 7 & 8.
> ECS templates for elasticsearch 8

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/data_stream_support.rb
- logstash-output-elasticsearch.gemspec
- spec/integration/outputs/data_stream_spec.rb
- spec/unit/outputs/elasticsearch/data_stream_support_spec.rb
- spec/unit/outputs/elasticsearch_spec.rb
When data streams were initially added to this output plugin, we had planned on ECS being on-by-default in Logstash 8, so it made sense to also have data streams be the default target. We had temporarily punted the switch for ECS in Logstash to a later date, which revealed that running very simple configs in the LS8 betas cause runtime mapping errors (typically caused by upstream plugins, also not operating in ECS-mode, introducing ECS-conflicts implicitly). Even though we are back on track for the undrerlying ECS changes to go into Logstash 8, it will be helpful to codify this requirement.
In order to set our users up for success, this plugin should avoid routing to data streams unless it is being run in an ECS compatibility mode (preferably derived from the `pipeline.ecs_compatibility` …
> Data streams require ECS

- docs/index.asciidoc
Current note formatting works, but isn't the best approach for simple notes. Fixing because formatting gets perpetuated in other places in docs.
> Doc: Fix note format

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch/http_client.rb
- lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb
- lib/logstash/outputs/elasticsearch/http_client/pool.rb
- logstash-output-elasticsearch.gemspec
- spec/integration/outputs/sniffer_spec.rb
- spec/unit/outputs/elasticsearch/http_client/manticore_adapter_spec.rb
- spec/unit/outputs/elasticsearch/http_client/pool_spec.rb
This PR moves adapter specific error mapping to the adapter itself.
Second, since Manticore now (>= 0.7.1) retains the [native Java cause](https://github.com/cheald/manticore/pull/96) with the `Manticore::ManticoreException` hierarchy, we also log the Java cause using the Log4J2 logger API (so that we're aware of the exception type, stack trace and any Java causes).
Example:
```
[2021-12-01T13:34:36,057][DEBUG][org.apache.http.conn.ssl.SSLConnectionSocketFactory][main] Starting handshake
[2021-12-01T13:34:36,125][DEBUG][org.apache.http.impl.conn.DefaultManagedHttpClientConnection][main] http-outgoing-0: Shutdown connection
[2021-12-01T13:34:36,126][DEBUG][org.apache.http.impl.execchain.MainClientExec][main] Connection discarded
[2021-12-01T13:34:36,126][DEBUG][org.apache.http.impl.conn.Poo …
```
> Refactor: review manticore error handling/logging

- CHANGELOG.md
- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch/data_stream_support.rb
- logstash-output-elasticsearch.gemspec
Adds support for 'traces' data stream type.
Related issue: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/1052
> Feat: add support for 'traces' data stream type

- CHANGELOG.md
- Rakefile
- logstash-output-elasticsearch.gemspec
- spec/es_spec_helper.rb
- spec/integration/outputs/ilm_spec.rb
- spec/integration/outputs/ingest_pipeline_spec.rb
- spec/integration/outputs/retry_spec.rb
Resolution of #1060.
With ECS 8.0, ECS is becoming Stack-aligned, and no longer generates template artifacts for other Elasticsearch majors. This is causing some paths to change in the upstream project from which we vendor our templates.
They continue to generate a monolith "legacy" template, for use with the Elasticsearch "legacy" template API (a.k.a., v1), but this plugin _automatically_ uses the v2 template endpoint when persisting templates to Elasticsearch 8.
Historically, this plugin has provided ECS v1 templates for (unreleased) Elasticsearch 8 by transforming them into the v2 format prior to vendoring. This changeset builds upon that work, renaming the relevant methods to be more descriptive and separating the concerns of transforming the template from those of defining which …
> ECS Templates: stack alignment

- CHANGELOG.md
- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/plugin_mixins/elasticsearch/api_configs.rb
- lib/logstash/plugin_mixins/elasticsearch/common.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/error_whitelist_spec.rb
Deprecates `failure_type_logging_whitelist` setting renaming it `silence_errors_in_log`
Introduce a new setting named `silence_errors_in_log` with exact same behavior of `failure_type_logging_whitelist`. It print a deprecation log message if `failure_type_logging_whitelist` is used.
Rename a setting that's generally confusing the user to a more meaningful name.
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding change to the default configuration files (and/or docker env variables)~~
- launch an ES instance, for example `docker-compose -f es_and_kb.yml up` 
[es_and_kb.txt](https://github.com/logstash-plugins/logstash-output-elasticsearch/files/8081186/es_and_kb.txt)
- from http://localhost:5601 Kibana UI (credential: elastic, …
> Deprecates option  in favor of `silence_errors_in_log`

- CHANGELOG.md
- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/plugin_mixins/elasticsearch/common.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch_spec.rb
Adds `dlq_custom_codes` option to customize the list of HTTP codes that are considered eligible for DLQ.
Introduced a new configuration option, named `dlq_custom_codes` which accepts a list of HTTP error codes.
The list is to be considered as an addition to the already existing codes that the plugin uses (DLQ_CODES, DOC_SUCCESS_CODES, DOC_CONFLICT_CODE defined in module `Common`). If the list has an intersection with those error codes then it's reported as a configuration error.
This is a feature requested in #697, in some cases some error codes returned by Elasticsearch should be handled as DLQ messaged and not retried for ever. For example writing to a read only index report a 403, the index status would never change automatically so it's best to move these events to DLQ for a later …
> Adds a new `dlq_custom_codes` option to customize DLQ codes

- CHANGELOG.md
- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/plugin_mixins/elasticsearch/common.rb
- logstash-output-elasticsearch.gemspec
- spec/integration/outputs/index_spec.rb
- spec/unit/outputs/elasticsearch_spec.rb
Modified the resolution of dynamic index name so that in case of interpolation errors the event is sent to the DLQ. This feature could be explicitly disabled configuring properly the `dlq_on_failed_indexname_interpolation`.
Update the the pre-indexing steps, so to that in case of an `IndexInterpolationError` is raised during the index name resolution, the event is sent to DLQ. It leverarges the refactored `#handle_dlq_status` from PR #1080 to reuse the enqueuing logic.
Let the user to handle specifically the events which once indexed would create an ugly formatted name like  `%{[not_existing_field]}_index`.
- ~~[ ] I have made corresponding change to the default configuration files (and/or docker env variables)~~
```
.ci/docker-setup.sh && INTEGRATION=true .ci/docker-run.sh
```
- enable …
> Route badly interpolated dynamic index to DLQ

- CHANGELOG.md
- README.md
- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/http_client.rb
- lib/logstash/plugin_mixins/elasticsearch/common.rb
- logstash-output-elasticsearch.gemspec
- spec/integration/outputs/index_spec.rb
- spec/integration/outputs/unsupported_actions_spec.rb
- spec/unit/outputs/elasticsearch/http_client_spec.rb
- spec/unit/outputs/elasticsearch_spec.rb
We have common logics with #1084, rebasing and leveraging the changes. 
Plugin receives `400 Validation Failed: 1: no requests added` exception when requesting unsupported bulk action.
This PR introduces a validation check on action before sending bulk request to ES.
Closes #1079 
- Used configuration to read from JSON file and send to ES. File contains an action field which is not in [`index`, `create`, `update`, `delete`]
```
input {
file {
path => "/path/to/files/*.json"
start_position => "beginning"
codec => "json"
}
}
output {
elasticsearch {
....
action => "%{[@metadata][action]}"
}
}
```
- Result
```
[2022-09-09T11:59:44,810][WARN ][logstash.outputs.elasticsearch][main][ca10f590b6ab3366bc38f754293adbd2499c9d97aedd7933d11542cd26cd056d] Could not index event to Elasticsearch because …
```
> Validate the action before sending the bulk request to ES.

- docs/index.asciidoc
We fixed a broken link in #1085 during a live demo, and introduced some unclear wording.  This PR fixes that.
No version bump/publish required for this change.
> Doc: Clarify wording on action option

- CHANGELOG.md
- lib/logstash/plugin_mixins/elasticsearch/common.rb
- logstash-output-elasticsearch.gemspec
- spec/integration/outputs/metrics_spec.rb
Introduces a new document metric name `dlq_routed` to count the events that are routed to DLQ.
Introduces a new document metric name `:dlq_routed` to be incremented every time an event is routed into DLQ.
Permit to understand how many events are directed into the DLQ.
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files (and/or docker env variables)~~
- enable DLQ in `config/logstash.yml` 
```yaml
dead_letter_queue.enable: true
```
- start an Elasticsearch with an index that result in DLQ routing. For example closed index:
```
PUT test_index/
POST test_index/_close
```
- create a config pipeline that sends event to the …
> Adds new counter to track events that are routed to DLQ

- CHANGELOG.md
- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/http_client.rb
- lib/logstash/outputs/elasticsearch/template_manager.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch/http_client_spec.rb
- spec/unit/outputs/elasticsearch/template_manager_spec.rb
Fixed: #1088
Prior to the change, the plugin uses legacy API for ES 7.x and forces to use index template API for ES 8.x. However, legacy template API is still available in ES 8 and user should be allowed to use it.
This commit adds a new flag `template_api` to control which API to use. The available value is `auto`, `legacy` and `composable`. The default value is `auto`.
- `auto` Logstash detect the version of Elasticsearch. It uses index template API for 8 and legacy API for 7. 
- `legacy` use legacy API
- `composable` use index template API
> Support legacy template api in elasticsearch 8

- .ci/logstash-run.sh
Fix: https://github.com/elastic/logstash/issues/14800
Use the bundler in `/vendor/bundle/jruby/2.6.0/bin/bundle` instead of `/vendor/jruby/bin/bundle` to run test, as Logstash doesn't package the latter in artifacts in https://github.com/elastic/logstash/pull/14667
> fix jruby bundler for test

- .ci/logstash-run.sh
- CHANGELOG.md
- docs/index.asciidoc
- logstash-output-elasticsearch.gemspec
Fixes the broken apache common http client link.
- Closes #1100 1100
- Broken: https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/conn/PoolingHttpClientConnectionManager.html#setValidateAfterInactivity(int)
- Suggesting: https://hc.apache.org/httpcomponents-client-4.5.x/current/httpclient/apidocs/org/apache/http/impl/conn/PoolingHttpClientConnectionManager.html#setValidateAfterInactivity(int)
> Fixes the broken apache common http client link.

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/data_stream_support.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch/data_stream_support_spec.rb
What this PR does?
- Refactored the [check_data_stream_config!](https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1109/files#diff-56fc556089a712f2ab141b29aa8363f8aaf2f3ee65360c538cc42245a0647ca9R53) method to reduce the cyclomatic complexity. 
- Changed the [data_stream_default](https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1109/files#diff-56fc556089a712f2ab141b29aa8363f8aaf2f3ee65360c538cc42245a0647ca9R161) log levels from `debug` to `info`. Those messages are helpful to users understanding the data stream auto-configuration mechanism/default and troubleshooting possibly incompatible settings.
- Logs were being printed twice due to a race condition on the `data_stream_config?` method, caused by the …
> Improve log messages for data stream support checks

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch/template_manager.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch/template_manager_spec.rb
When installing the template (either custom or auto resolved), sometimes there is a mismatch. For example, without this change, the case with `template_api=>'legacy'` connecting to ES 8+ resolves the wrong ILM setting field and crashes.
This change introduces ILM setting resolution based on custom/loaded template or/and `template_api` settings.
For the given any settings, including custom template or/and `template_api`, plugin needs to resolve ILM setting instead crashing.
- Unit tests
```
Finished in 1 minute 22.92 seconds (files took 7.1 seconds to load)
269 examples, 0 failures
Randomized with seed 22550
```
- Closes #1108
- Closes #1040
--- 
_History_
The change mainly solves two problems:
1. the plugin crashes when resolving and installing default template using legacy template …
> Resolve ILM settings based loaded template or/and `template_api`

- CHANGELOG.md
- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/http_client_builder.rb
- lib/logstash/plugin_mixins/elasticsearch/api_configs.rb
- lib/logstash/plugin_mixins/elasticsearch/common.rb
- logstash-output-elasticsearch.gemspec
- spec/integration/outputs/index_spec.rb
- spec/unit/outputs/elasticsearch/data_stream_support_spec.rb
- spec/unit/outputs/elasticsearch_spec.rb
- spec/unit/outputs/elasticsearch_ssl_spec.rb
Added the following SSL settings: 
`ssl_truststore_type`: The format of the truststore file
`ssl_keystore_type`: The format of the keystore file
`ssl_certificate`: OpenSSL-style X.509 certificate file to authenticate the client
`ssl_key`: OpenSSL-style RSA private key that corresponds to the `ssl_certificate`
`ssl_cipher_suites`: The list of cipher suites
Reviewed and deprecated the following SSL settings to comply with Logstash's naming convention:
`ssl` in favor of `ssl_enabled`
`cacert` in favor of `ssl_certificate_authorities`
`keystore` in favor of `ssl_keystore_path`
`keystore_password` in favor of `ssl_keystore_password`
`truststore` in favor of `ssl_truststore_path`
`truststore_password` in favor of `ssl_truststore_password`
`ssl_certificate_verification` in favor of …
> Standardize and add SSL settings

- CHANGELOG.md
- logstash-output-elasticsearch.gemspec
Fixed the `11.14.0` changelog entry, the correct PR link is #1118 instead of #1115.
---
https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1118#discussion_r1144004936
> Fix 11.14.0 CHANGELOG PR link

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/plugin_mixins/elasticsearch/common.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch_spec.rb
Introduce the ability to negatively acknowledge the batch under processing if the plugin is blocked in a retry-error-loop and a shutdown is requested.
Updates the wait_for_successful_connection method and safe_bulk to react to shutdown requests.
When the plugin is in a retry loop and Logstash it's running into provide the ability to negatively ACK the batch under processing and a pipeline shutdown was requested then the plugin terminate signalling that the batch under processing shouldn't be acknowledged, raising an AbortedBatchException.
Let the user to update the configuration of the plugin, when managed by CPM, resuming from a retry-loop due to bad configuration values (or expired credentials);
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made …
> Check pipeline shutdown status while waiting for valid connection or while issuing a bulk to ES

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch.rb
- logstash-output-elasticsearch.gemspec
- spec/integration/outputs/templates_spec.rb
- spec/unit/outputs/elasticsearch_spec.rb
This PR fixes a race condition between the thread running `register` and the one running `finish_register`.
The issue can be observed by having 20-30 simple pipelines in `pipelines.yml` like:
```
input {
java_generator { eps => 1.1 }
}
output {
elasticsearch {
user => elastic
password => ".."
data_stream => true
}
```
```yml
- pipeline.id: test_0
pipeline.workers: 1
pipeline.batch.size: 1
path.config: "/tmp/logstash-8.7.0/cfg"
```
```
ruby -ryaml -e '30.times.each {|i| puts "- pipeline.id: test_#{i}\n  pipeline.workers: 1\n  pipeline.batch.size: 1\n  path.config: \"/tmp/logstash-8.7.0/cfg\""}' > config/pipelines.yml
```
Run Logstash w/ pipeline reloading:
```
bin/logstash -r
```
Changing the pipeline config a few times and letting Logstash reload will eventually show one or more pipelines …
> move async finish_register to bottom of register to avoid race condition

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/plugin_mixins/elasticsearch/common.rb
- spec/es_spec_helper.rb
- spec/integration/outputs/templates_spec.rb
- spec/unit/outputs/elasticsearch_spec.rb
Alternative to #1104.
I authored this before getting derailed by a more urgent task, and just saw that @andsel had replicated my work in my off-hours. 
In this variant, because the `Elasticsearch#handle_event_mapping_errors` _already_ was making decisions based on the value of `@dlq_writer`, I didn't see the need to constrain the already-leaked DLQ abstraction to `Elasticsearch::Common#handle_dlq_status` and felt that working with `@dlq_writer` directly was more readable and easier to make sense of.
----
Fixes: #1103
> dlq-logging: reintroduce structured payload where possible

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch.rb
- logstash-output-elasticsearch.gemspec
ECS `8.7.0` released but still we are warning about `8.0.0` unreleased preview message. This PR simply removes the warning which gives end-users confusion.
- Closes https://github.com/elastic/logstash/issues/15011
> Remove ECS v8 unreleased preview warning message.

- CHANGELOG.md
- lib/logstash/plugin_mixins/elasticsearch/common.rb
- logstash-output-elasticsearch.gemspec
When plugin check if shutdown is received, it tries to call [`shutdown_requested?` java API](https://github.com/mashhurs/logstash/blob/6ab14e4e8a8c25ab8b6229b19923564e735a6fa0/logstash-core/src/main/java/org/logstash/execution/AbstractPipelineExt.java#L819) but in ruby code we are missing `?` mark after method. Since there is no `shutdown_requested` in core, plugin stops with the `(NoMethodError) undefined method 'shutdown_requested'` error.
- Closes: #1133
> Fixes the undefined `shutdown_requested` method error.

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch_spec.rb
Fix the abort of batch also when the ES connection is alive and the processing should continue.
Fixes the exit condition while waiting for valid connection. It could happen that while waiting both conditions becomes true:
- a connection was established
- the shutdown was requested
If the shutdown is requested *and* a valid ES connection is created the processing must take place and shouldn't abort the batch.
While waiting for connection to be established, the busy wait loop that also check for shutdown request. The abort of the batch should happen if no connection was successful established and there is a shutdown request; else it could be that the loop exit condition is trigger with both parts satisfied and it's not correct to abort the batch if a connection was created.
In this …
> Fixed abort condition in case of shutdown is requested during connection wait

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/plugin_mixins/elasticsearch/api_configs.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch/data_stream_support_spec.rb
move dlq_ setting definition to shared parameters (could be used by other ES outputs) so it is allowed to work with data streams
fixes https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/1135
> allow dlq_ settings when using data streams

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch/http_client.rb
- lib/logstash/outputs/elasticsearch/http_client/pool.rb
- lib/logstash/outputs/elasticsearch/ilm.rb
- lib/logstash/outputs/elasticsearch/license_checker.rb
- lib/logstash/outputs/elasticsearch/template_manager.rb
- lib/logstash/plugin_mixins/elasticsearch/common.rb
- logstash-output-elasticsearch.gemspec
- spec/es_spec_helper.rb
- spec/fixtures/license_check/active.json
- spec/fixtures/license_check/inactive.json
- spec/unit/outputs/elasticsearch/http_client/pool_spec.rb
- spec/unit/outputs/elasticsearch/template_manager_spec.rb
- spec/unit/outputs/license_check_spec.rb
The pool stores build flavour in health check to determinate if the Elasticsearch is serverless.
In serverless, ilm, legacy template API and license checker are disabled. The plugin throws ConfigurationError when ilm_enabled => true or template_api => legacy
todo: add integration test against serverless 
fixes: https://github.com/elastic/ingest-dev/issues/2277
> Add support to Serverless Elasticsearch

- CHANGELOG.md
- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/http_client.rb
- lib/logstash/outputs/elasticsearch/http_client_builder.rb
- lib/logstash/plugin_mixins/elasticsearch/api_configs.rb
- logstash-output-elasticsearch.gemspec
- spec/integration/outputs/compressed_indexing_spec.rb
- spec/integration/outputs/index_spec.rb
- spec/unit/outputs/elasticsearch/http_client_spec.rb
- spec/unit/outputs/elasticsearch_spec.rb
This commit deprecated `http_compression` in favor of `compression_level`.
http_compression `false` mapped to compression_level `0`, and `true` mapped to `1`.
The default setting has changed from disabling compression to enabling compression at level 1 (best speed)
Fix: https://github.com/elastic/ingest-dev/issues/2217
> Add http compression level

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch.rb
- lib/logstash/outputs/elasticsearch/http_client.rb
- lib/logstash/outputs/elasticsearch/http_client/pool.rb
- lib/logstash/plugin_mixins/elasticsearch/common.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch/http_client/pool_spec.rb
- spec/unit/outputs/elasticsearch/http_client_spec.rb
This commit adds "Elastic-Api-Version" : "2023-10-31" to request header when the Elasticsearch is serverless
Rename "flavour" to "flavor"
> Add Elastic Api Version header

- CHANGELOG.md
- docs/index.asciidoc
- lib/logstash/plugin_mixins/elasticsearch/api_configs.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/error_whitelist_spec.rb
The example reported in documentation for the setting [`silence_errors_in_log`](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-silence_errors_in_log) does not appear to work with modern version of Elasticsearch. The correct value should be `version_conflict_engine_exception`, which as per  https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/ElasticsearchException.java#L1271C1-L1272C replaced the exception `document_already_exist_exception`.
This PR replace in the example for silence_errors_in_log the deprecated/not more existent `document_already_exist_exception` with the value `version_conflict_engine_exception`.
> Replace document_already_exist_exception with version_conflict_engine_exception in the silence_errors_in_log setting example

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch_spec.rb
Use integration metadata to interact with Elasticsearch.
Change the creation of actions that are passed down to Elasticsearch to use also the metadata fields set by an integration.
The interested fields are `id` (document_id), `index` and `pipeline`, the field values are taken verbatim without placeholders resolution.
The index, document_id and pipeline that are configured in the plugin settings have precedence on the integration ones because manifest an explicit choice made by the user.
This PR fixes an interoperability issue with Agent's integrations, where some metadata valued by integration has to be used down to Elasticsearch.
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files (and/or docker env …
> Use integration metadata to create ES actions

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch_spec.rb
Added support for propagating event processing metadata when this output is downstream of an Elastic Integration Filter and configured _without_ explicit `version`, `version_type`, or `routing` directives
Change the creation of actions that are passed down to Elasticsearch to use also the metadata fields set by an integration.
The interested fields are `version`, `version_type` and `routing`, the field values are taken verbatim without placeholders resolution.
The version, version_type and routing that are configured in the plugin settings have precedence on the integration ones because manifest an explicit choice made by the user.
This PR complete the fix related to interoperability issue with Agent's integrations (started with #1155), where some metadata valued by integration has to be …
> Use integration metadata to create ES actions (part 2)

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch_spec.rb
Avoid to populate version and version type attributes when processing integration metadata and datastream is enabled
During PR #1155 the resolution of `version` and `version_type` ES parameters was moved from the index only event action tuple creation to the common method. This changed was due to do the intent to collect all integration-aware metadata fields in one place, but the common method is used also by the datastream part this result in populating `event` and `event_type` request parameters not only for normal index operations. 
During an index operation on a datastream, if one of those parameters is valued, generated an error on ES indexing, resulting in request fail.
This PR move the processing and creation of event and event_type parameters, back in its original position, …
> When datastream is enabled then no version related attributes fills into document actions

- CHANGELOG.md
- docs/index.asciidoc
- logstash-output-elasticsearch.gemspec
Closes: #1149 
Replaces: #1150
Update logstash-output-elasticsearch docs to raise visibility that Elasticsearch on serverless is an output option, and provide guidelines and requirements for users who want to use that option.
> Doc: Add notes and guidelines for elasticsearch svrless

- .ci/docker-run.sh
- .ci/docker-setup.sh
> Attach only logstash container logs to limit the log fload.

- .ci/docker-setup.sh
- CHANGELOG.md
- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch/http_client.rb
- logstash-output-elasticsearch.gemspec
- spec/integration/outputs/compressed_indexing_spec.rb
- spec/unit/outputs/elasticsearch/http_client_spec.rb
See [origin PR](https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1169) for the details, applying to 11.4.x versions to be available in LS 7.17.x core
> (backport: 11.4 for LS7.x) Fixes an issue where events containing non-unicode strings.

- CHANGELOG.md
- The changelog on `main` had a docs-only entry for `11.4.2` that was not packaged and released until `11.5.0`; update the changelog to reflect where it was actually packaged
- We recently _backported_ a fix that was first available in `v11.22.3` to a new `11.4-maintenance` branch (cut from the `v11.4.1` tag), and released that fix with `v11.4.2`; we forward-port its changelog entry to `main`, along with a caveat so that users don't assume the fix's availability in intermediate releases.
> Resync CHANGELOG

- CHANGELOG.md
- docs/index.asciidoc
- logstash-output-elasticsearch.gemspec
> Doc: Add notice that ecs compatibility is required for data streams

- CHANGELOG.md
- docs/index.asciidoc
- logstash-output-elasticsearch.gemspec
copy the doc from [beat-input ](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-beats.html#plugins-inputs-beats-ssl_key)ssl_key
> [Doc] `ssl_key` requires PKCS#8 format

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch/templates/ecs-disabled/elasticsearch-9x.json
- logstash-output-elasticsearch.gemspec
Logstash `main` points to ES v9 and needs this template.
> Added template for ES v9

- CHANGELOG.md
- Rakefile
- logstash-output-elasticsearch.gemspec
Vendor ECS template for Elasticsearch 9.x in built gem
Update `Rakefile` to vendor ECS schema template v8 for Elasticsearch 9
Let the plugin work with Elaticsearch 9 templates
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files (and/or docker env variables)~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- vendor the gem
```sh
rake vendor
gem build 
```
- unpack the gem and verify that  contains the templates
```sh
gem unpack logstash-output-elasticsearch-11.22.9-java.gem
tree logstash-output-elasticsearch-11.22.8-java/lib/logstash/outputs/elasticsearch/templates/
```
- Relates #1187
``` …
```
> Vendor Elasticsearch 9 templates in the generated gem

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb
- logstash-output-elasticsearch.gemspec
- spec/integration/outputs/compressed_indexing_spec.rb
- spec/integration/outputs/index_spec.rb
- spec/unit/outputs/elasticsearch/http_client/manticore_adapter_spec.rb
This commit updates the `Elasticsearch::Client` used to make requests to ES to
send along a header identifying the request as originating from an internal
component.
closes https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/1191
> Set x-elastic-product-origin header for ES requests

- CHANGELOG.md
Changelog entry merged in #1195 incorrectly links to #1194 which is still WIP. 
If we go with this approach to make the correction, we'll have to fix it again in release notes for all releases that are locked to this plugin version.
> Update CHANGELOG.md to fix PR number and link

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch/http_client/pool.rb
- logstash-output-elasticsearch.gemspec
This commit removes an old warning which is no longer relevant to any supported
stack version. It is noisy and there is no action for the user to take.
Closes https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/1198
> Remove irrelevant warning

- CHANGELOG.md
- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch/http_client.rb
- lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb
- lib/logstash/outputs/elasticsearch/http_client/pool.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch_spec.rb
Previously when Elasticsearch responds with a 413 (Payload Too Large) status,
the manticore adapter raises an error before the response can be processed
by the bulk_send error handling. This commit refactors the way
`BadErrorResponse` codes are handled. Previously we had logic in the manticore
adaptor which special cased raising errors on some codes. This commit refactors
such that the adaptor raises on any error status and the caller is now
responsible for special case handling the code.
> Properly handle 413 Payload Too Large errors

- CHANGELOG.md
- docs/index.asciidoc
- lib/logstash/outputs/elasticsearch/http_client.rb
- lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb
- lib/logstash/outputs/elasticsearch/http_client/pool.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch_spec.rb
Backport of https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1199
> Backport #1199 Properly handle 413 Payload Too Large errors (#1199)

- lib/logstash/outputs/elasticsearch/http_client/pool.rb
This will prevent logstash from throwing a warning if connecting is an expected behaviour.
> Demote WARN to INFO if behaviour is expected for connect.

- CHANGELOG.md
- lib/logstash/outputs/elasticsearch/http_client_builder.rb
- spec/unit/http_client_builder_spec.rb
Avoid double-encoding opaque Elasticsearch API keys.
Previously, API keys that were already in encoded format were incorrectly re-encoded, causing connection failures. This update ensures that only raw keys are encoded, supporting both opaque and `id:api-key` formats without issue.
Closes [#1222](https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/1222)
> Support both, encoded and non encoded api-key formats on plugin configuration

- CHANGELOG.md
- docs/index.asciidoc
- lib/logstash/plugin_mixins/elasticsearch/api_configs.rb
- lib/logstash/plugin_mixins/elasticsearch/common.rb
- logstash-output-elasticsearch.gemspec
- spec/unit/outputs/elasticsearch_spec.rb
This PR adds a config option `drop_error_types` that allows a user to set a list of error types for which a failed bulk request should not be retried and the events should be dropped. The events are not added to the DLQ. A warn message is logged, if the error type is not listed in the config option `silence_errors_in_log`.
Closes #1225
> Add drop_error_types config option to not retry after certain error types
